name: Test Node.js App with Health Check

on:
  push:
    branches:
      - main

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Start App in Background
      run: npm start &

    - name: Check Health Endpoint
      run: |
        sleep 5  # Wait for the server to start
        STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/health)
        if [ "$STATUS_CODE" -eq 200 ]; then
          echo "Health check passed with status code: $STATUS_CODE"
        else
          echo "Health check failed with status code: $STATUS_CODE"
          exit 1
        fi
